export const jugadores = [
  {
    nombre: "Lionel Messi",
    edad: 36,
    nacionalidad: "Argentina",
    equipo: "Inter Miami",
    posición: "Delantero",
  },
  {
    nombre: "Cristiano Ronaldo",
    edad: 39,
    nacionalidad: "Portugal",
    equipo: "Al-Nassr",
    posición: "Delantero",
  },
  {
    nombre: "Neymar Jr.",
    edad: 32,
    nacionalidad: "Brasil",
    equipo: "Al-Hilal",
    posición: "Delantero",
  },
  {
    nombre: "Kylian Mbappé",
    edad: 25,
    nacionalidad: "Francia",
    equipo: "Paris Saint-Germain",
    posición: "Delantero",
  },
  {
    nombre: "Kevin De Bruyne",
    edad: 32,
    nacionalidad: "Bélgica",
    equipo: "Manchester City",
    posición: "Centrocampista",
  },
  {
    nombre: "Virgil van Dijk",
    edad: 32,
    nacionalidad: "Países Bajos",
    equipo: "Liverpool",
    posición: "Defensor",
  },
  {
    nombre: "Robert Lewandowski",
    edad: 35,
    nacionalidad: "Polonia",
    equipo: "FC Barcelona",
    posición: "Delantero",
  },
  {
    nombre: "Sergio Ramos",
    edad: 37,
    nacionalidad: "España",
    equipo: "Sevilla",
    posición: "Defensor",
  },
  {
    nombre: "Luka Modrić",
    edad: 38,
    nacionalidad: "Croacia",
    equipo: "Real Madrid",
    posición: "Centrocampista",
  },
  {
    nombre: "Harry Kane",
    edad: 30,
    nacionalidad: "Inglaterra",
    equipo: "Bayern Múnich",
    posición: "Delantero",
  },
  {
    nombre: "Erling Haaland",
    edad: 23,
    nacionalidad: "Noruega",
    equipo: "Manchester City",
    posición: "Delantero",
  },
  {
    nombre: "Sadio Mané",
    edad: 32,
    nacionalidad: "Senegal",
    equipo: "Al-Nassr",
    posición: "Delantero",
  },
  {
    nombre: "Mohamed Salah",
    edad: 31,
    nacionalidad: "Egipto",
    equipo: "Liverpool",
    posición: "Delantero",
  },
  {
    nombre: "Antoine Griezmann",
    edad: 33,
    nacionalidad: "Francia",
    equipo: "Atlético de Madrid",
    posición: "Delantero",
  },
  {
    nombre: "Thibaut Courtois",
    edad: 31,
    nacionalidad: "Bélgica",
    equipo: "Real Madrid",
    posición: "Portero",
  },
  {
    nombre: "Jan Oblak",
    edad: 31,
    nacionalidad: "Eslovenia",
    equipo: "Atlético de Madrid",
    posición: "Portero",
  },
  {
    nombre: "Paul Pogba",
    edad: 31,
    nacionalidad: "Francia",
    equipo: "Juventus",
    posición: "Centrocampista",
  },
  {
    nombre: "Joshua Kimmich",
    edad: 29,
    nacionalidad: "Alemania",
    equipo: "Bayern Múnich",
    posición: "Centrocampista",
  },
  {
    nombre: "Jadon Sancho",
    edad: 24,
    nacionalidad: "Inglaterra",
    equipo: "Manchester United",
    posición: "Delantero",
  },
  {
    nombre: "Trent Alexander-Arnold",
    edad: 25,
    nacionalidad: "Inglaterra",
    equipo: "Liverpool",
    posición: "Defensor",
  },
  {
    nombre: "Alphonso Davies",
    edad: 23,
    nacionalidad: "Canadá",
    equipo: "Bayern Múnich",
    posición: "Defensor",
  },
  {
    nombre: "Raheem Sterling",
    edad: 29,
    nacionalidad: "Inglaterra",
    equipo: "Chelsea",
    posición: "Delantero",
  },
  {
    nombre: "Bruno Fernandes",
    edad: 29,
    nacionalidad: "Portugal",
    equipo: "Manchester United",
    posición: "Centrocampista",
  },
  {
    nombre: "Kai Havertz",
    edad: 24,
    nacionalidad: "Alemania",
    equipo: "Arsenal",
    posición: "Centrocampista",
  },
  {
    nombre: "Phil Foden",
    edad: 24,
    nacionalidad: "Inglaterra",
    equipo: "Manchester City",
    posición: "Centrocampista",
  },
  {
    nombre: "Ruben Dias",
    edad: 26,
    nacionalidad: "Portugal",
    equipo: "Manchester City",
    posición: "Defensor",
  },
  {
    nombre: "Gianluigi Donnarumma",
    edad: 25,
    nacionalidad: "Italia",
    equipo: "Paris Saint-Germain",
    posición: "Portero",
  },
  {
    nombre: "Marcus Rashford",
    edad: 26,
    nacionalidad: "Inglaterra",
    equipo: "Manchester United",
    posición: "Delantero",
  },
  {
    nombre: "Frenkie de Jong",
    edad: 27,
    nacionalidad: "Países Bajos",
    equipo: "FC Barcelona",
    posición: "Centrocampista",
  },
  {
    nombre: "Edouard Mendy",
    edad: 32,
    nacionalidad: "Senegal",
    equipo: "Chelsea",
    posición: "Portero",
  },
].sort((a, b) => a.nombre.localeCompare(b.nombre));
